### PR TITLE
Add stun and mdns repositories

### PR DESCRIPTION
**Pull request by at-wat**
Sync CI config to pion/stun and pion/mdns.

### CODE REVIEW

**Comment by at-wat** [comment]
pion/stun repository has a repository specific codecov.yml with higher threshold.

**Comment by at-wat** [comment]
https://github.com/at-wat/assets-sync-action/issues/11

**Comment by Sean-Der** [comment]
@at-wat has lots of problems we need to fix :/ I haven't gotten around to it.

We had a version of `pion/stun` before, but we replaced it with gortc's. The hope was that both projects would then combine, however we couldn't agree on things and the process stopped :(

At this point the project is sort of in limbo. Eventually we need to massively cleanup the repo and bring it inline with everything else. I wouldn't put much effort into it now though, not much churn so I don't see much value!

**Comment by at-wat** [comment]
Now, `assets-sync-action` can exclude specified path.

**Pull request merged**
