### PR TITLE
Check API compatability guarantees

### PR DESCRIPTION
**Pull request by stv0g**

### CODE REVIEW

**Review by at-wat — COMMENTED** [review]
Looks convenient to check API compatibility automatically

How the check results will be shown?
Isn't it better to have separated CI job to only check API compatibility?

**Comment by at-wat** [comment]
I think printing result in a step of the long log is too hard for notifying maintainers about the API breakage and can be overlooked in most time

**Comment by stv0g** [comment]
Let me check, but I was under the assumption that a breaking change will return a non-zero exit code and hence make the test fail.

This could only be solved by making the changes API compatible, or introducing a new major version.

**Comment by stv0g** [comment]
@at-wat I've confirmed that incompatible changes which result in exit code == 1. Hence the test will fail and maintainers are clearly aware of breaking changes.

**Comment by at-wat** [comment]
> I've confirmed that incompatible changes which result in exit code == 1. Hence the test will fail and maintainers are clearly aware of breaking changes.

So, PRs with breaking changes never pass CI since PRs don't have information about major version bump after merging?

**Comment by stv0g** [comment]
> So, PRs with breaking changes never pass CI since PRs don't have information about major version bump after merging?

Mhh, okay. Thats indeed currently broken. `go-apidiff` rightfully treats a major version bumb of the module as a new module and therefore complains that basically all types/functions of the old module have been removed.

We need to add an exception here to allow major version bumps to break the API.
Detecting a `v1` -> `v2` bump is easy. We can just look at `go.mod`.
However, a `v0` -> `v1` is difficult, as we must take the latest Git version tag into account. However, I assume that this tag does not exist yet at the time, the CI runs :(

@at-wat Do you have an idea how we could fix this? I am willing to contribute a new `--allow-incompatible-change-on-major-version-bump` flag to `go-apidiff` if we can work it out :)

But i think, that we would also be fine to either:
- Allowing this step of the workflow to fail, and just show a big warning
- Make it mandatory for repo/org owners to bypass this failing tests for major version bumps. I think it would be anyway good to have a safeguard or additional hurdle to bump the major version of a model.

**Comment by at-wat** [comment]
IMO, forcing major version bump on API breakage is better, however currently `pion/webrtc` repository often have breaking changes on minor/patch release.
@Sean-Der what do you think of the change of the versioning policy?

**Comment by Sean-Der** [comment]
@at-wat i agree! It is bad that we break API without bumping.

I love having checks to make sure we do this right

**Comment by at-wat** [comment]
@stv0g 
We usually hold multiple API breaking changes and release them as a single major version bump.
So, I think this should be used along with Conventional Commit and allow API breaking changes only when commit message has `BREAKING CHANGE:` footer or `!` commit type suffix.
Then, the next release which contains at least one breaking change results major version bump

**Review by Sean-Der — APPROVED** [review]

**Pull request merged**
